name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - jupyterlab=1.1
  - matplotlib=3.1
  - pandas=0.25
  - pyarrow=0.14
  - python=3.7
  - scikit-learn=0.21
  - xlrd=1.2
  - fbprophet 0.5
  - plotly 4.3
  - statsmodels
